package fi.uta.fsd.metka.storage.variables.enums;

public enum ParseResult {
    NO_VARIABLES_FILE,
    DID_NOT_FIND_VARIABLES_FILE,
    VARIABLES_FILE_HAD_NO_PATH,
    COULD_NOT_CREATE_VARIABLES,
    NO_TYPE_GIVEN,
    DID_NOT_FIND_VARIABLES,
    NO_CHANGES,
    REVISION_CHANGES,
    VARIABLES_SERIALIZATION_FAILED,
    DID_NOT_FIND_VARIABLE,
    NO_VARIABLES_CONTAINER,
    COULD_NOT_CREATE_VARIABLE_DRAFT,
    DID_NOT_FIND_STUDY,
    NO_DEFAULT_VARIABLES,
    COULD_NOT_CREATE_VARIABLES_DRAFT
}
